# Docker Compose: Web services
# <MARIADB_ROOT>
# <MARIADB_NEXTCLOUD>
# <SAMBA_NAS>
# <SAMBA_SCANNER>
# <PLEX_CLAIM>
# <PLEX_IP>
---
version: '3'

services:
  
#########################
#          WEB          #
#########################
  le:
    image: linuxserver/letsencrypt
    container_name: le
    restart: always
    networks:
      - web
    ports:
      - "443:443"
    volumes:
      - /opt/appdata/letsencrypt:/config
    depends_on:
      - portainer
      - torrent
      - nextcloud
    environment:
      - PUID=233
      - PGID=233
      - EMAIL=jens@jensw.be
      - URL=jensw.eu
      - SUBDOMAINS=admin,torrent,nextcloud
      - TZ=Europe/Brussels

  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always
    privileged: true
    networks:
      - web
    expose:
      - "9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/appdata/portainer:/data

  torrent:
    image: linuxserver/deluge
    container_name: torrent
    network_mode: "host"
    restart: always
    volumes:
      - "/media/data/services/torrent/:/running"
      - "/media/data/media/000. Plex/Nazien:/downloads"
      - "/opt/appdata/torrent:/config"
    environment:
      - PUID=233
      - PGID=233
      - TZ=Europe/Brussels
  
  nextcloud:  
    image: nextcloud
    container_name: nextcloud
    restart: always
    networks:
      - web
      - db
    expose:
      - "80"
    depends_on:
      - mariadb
    volumes:
      - /opt/appdata/nextcloud:/var/www/html
      - /media/data/services/nextcloud:/var/www/html/data

  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    networks:
      - db
    volumes:
      - /opt/appdata/mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=<MARIADB_ROOT>
      - MYSQL_PASSWORD=<MARIADB_NEXTCLOUD>
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

#########################
#        SAMBA          #
#########################
  samba:
    image: dperson/samba
    container_name: samba
    restart: always
    networks: ["samba"]
    ports:
      - "192.168.1.250:139:139"
      - "192.168.1.250:445:445"
    volumes:
      - /media/data/media:/mnt/media
    environment:
      - USERID=233
      - GROUPID=233
    command: samba.sh -S -u "nas;<SAMBA_NAS>" -u "scanner;<SAMBA_SCANNER>" -s "media;/mnt/media;yes;no;no;nas" -s "scans;/mnt/media/Scans;yes;no;no;scanner"

#########################
#         PLEX          #
#########################
  plex:
    image: plexinc/pms-docker
    container_name: plex
    restart: always
    network_mode: "host"
    volumes:
      - "/media/data/media/000. Plex:/data/media"
      - /media/data/media-plex-optimized/:/data/optimized
      - /opt/appdata/plex/config:/config
      - /opt/appdata/plex/transcode:/transcode
    environment:
      - TZ=Europe/Brussels
      - PLEX_CLAIM=<PLEX_CLAIM>
      - PLEX_UID=233
      - PLEX_GID=233
      - ADVERTISE_IP="<PLEX_IP>"

networks:
  web:
  db:
  samba:
