debug = false

logLevel = "ERROR"
defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]
#  [entryPoints.traefik]
#  address = ":8080"

[retry]

# [traefikLog]

# [accessLog]

################################################################
# Web configuration backend
################################################################

# Enable web configuration backend
# https://docs.traefik.io/configuration/api/
#[api]
#entryPoint = "traefik"
#dashboard = true

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "jensw.eu"
watch = true
exposedbydefault = false

[acme]
email = "admin@jensw.be"
storage = "/etc/traefik/acme/acme.json"
entryPoint = "https"
OnHostRule = true
[acme.httpChallenge]
entryPoint = "http"
