debug = true

logLevel = "DEBUG"
defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]

[retry]

################################################################
# Web configuration backend
################################################################

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "jensw.eu"
watch = true
exposedbydefault = false

[acme]
email = "admin@jensw.be"
storage = "/etc/traefik/acme/acme.json"
entryPoint = "https"
  [acme.dnsChallenge]
    provider = "cloudflare"
    delayBeforeCheck = 0

[[acme.domains]]
  main = "*.jensw.eu"
  sans = ["jensw.eu"]
